/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:9f874540-ed7a-4227-9889-7d0263b28546",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_AO9GN7Zio",
    "aws_user_pools_web_client_id": "5qin20197201n4ai9tuk1jel6j",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "FAMILY_NAME",
        "GIVEN_NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "splitr",
            "endpoint": "https://eawc5goc3j.execute-api.us-west-1.amazonaws.com/dev",
            "region": "us-west-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "splitr-dev",
            "region": "us-west-1"
        }
    ],
    "aws_user_files_s3_bucket": "splitr-storage222809-dev",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
